services:
  - type: web
    name: thecuthub
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/data/app.db
      - key: DB_PROVIDER
        value: sqlite
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
